"""
Baseline method wrappers for EVRP-TW experiments.

This module provides a unified interface for running different baseline
methods. In Week 2, we start with the greedy baseline developed in Week 1.
Later, additional baselines such as OR-Tools, ALNS, or neural construction
methods can be added here.

The goal is to make all baseline methods return results in a comparable format.
"""

from dataclasses import dataclass
from time import perf_counter
from typing import Any

from src.evaluator import evaluate_solution
from src.greedy import build_greedy_solution
from src.instance import EVRPTWInstance
from src.solution import Solution


@dataclass
class BaselineRunResult:
    """
    Stores the output of one baseline run.

    Attributes
    ----------
    method_name:
        Name of the baseline method.

    solution:
        The routing solution generated by the baseline.

    evaluation:
        Evaluation result returned by the evaluator.

    runtime_seconds:
        Wall-clock runtime of the baseline method.

    metadata:
        Optional dictionary for storing extra information, such as parameters.
    """

    method_name: str
    solution: Solution
    evaluation: Any
    runtime_seconds: float
    metadata: dict[str, Any]


def run_greedy_baseline(instance: EVRPTWInstance) -> BaselineRunResult:
    """
    Run the greedy baseline on an EVRP-TW instance.

    The greedy baseline is currently used as the first reproducible baseline.
    It constructs a solution using a simple heuristic and then evaluates it
    using the common evaluator.

    Parameters
    ----------
    instance:
        EVRP-TW instance to solve.

    Returns
    -------
    BaselineRunResult
        A structured result containing the solution, evaluation result,
        runtime, and metadata.
    """

    start_time = perf_counter()

    solution = build_greedy_solution(instance)
    evaluation = evaluate_solution(instance, solution)

    end_time = perf_counter()
    runtime_seconds = end_time - start_time

    return BaselineRunResult(
        method_name="greedy",
        solution=solution,
        evaluation=evaluation,
        runtime_seconds=runtime_seconds,
        metadata={
            "description": "Greedy construction baseline",
            "instance_name": instance.name,
            "customer_count": len(instance.customers),
            "station_count": len(instance.stations),
            "vehicle_count": instance.vehicle_count,
        },
    )


def run_baseline(method_name: str, instance: EVRPTWInstance) -> BaselineRunResult:
    """
    Run a baseline method by name.

    This function makes the experiment pipeline more scalable. Instead of
    manually calling different baseline functions in scripts, we can use
    one unified interface.

    Parameters
    ----------
    method_name:
        Name of the baseline method. Currently supported:
        - "greedy"

    instance:
        EVRP-TW instance to solve.

    Returns
    -------
    BaselineRunResult
        Result of the selected baseline method.

    Raises
    ------
    ValueError
        If the method name is not supported.
    """

    normalized_name = method_name.lower().strip()

    if normalized_name == "greedy":
        return run_greedy_baseline(instance)

    raise ValueError(
        f"Unknown baseline method: {method_name}. "
        f"Currently supported methods: ['greedy']."
    )